language: java
git:
 depth: 1
jdk:
 - oraclejdk8
dist: trusty
env:  
 global:  
  - DISPLAY=:99.0  
before_install:  
 - sh -e /etc/init.d/xvfb start - sleep 10  
cache:  
 directories:  
 - $HOME/.m2  

